[workspace]
members = [".", "crates/app_macros"]

[package]
name = "app"
version = "0.1.0"
edition = "2024"
rust-version = "1.85" # 1.100.0-nightly
description = "Gui application for editing and reading structured data."
license = "Apache-2.0"
repository = "https://github.com/animagram-jp/app"
readme = "CONTRIBUTING.md"
exclude = ["examples/", "distribution/", "docs/"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
app_macros    = { path = "crates/app_macros" }
arbitrary-int = "2"
wasm-bindgen         = { version = "0.2", default-features = false }
wasm-bindgen-futures = { version = "0.4", default-features = false }
js-sys               = { version = "0.3", default-features = false }
web-sys = { version = "0.3", default-features = false, features = [
    "WorkerGlobalScope",
    "WorkerNavigator",
    "StorageManager",
    "FileSystemDirectoryHandle",
    "FileSystemGetFileOptions",
    "FileSystemFileHandle",
    "FileSystemReadWriteOptions",
    "FileSystemSyncAccessHandle",
    "DomException",
] }
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
rand  = { version = "0.10", default-features = false, features = ["alloc", "sys_rng"] }
log   = { version = "0.4", default-features = false, optional = true }
libm  = { version = "0.2", default-features = false }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom     = { version = "0.4", default-features = false, features = ["wasm_js"] }
talc          = { version = "5.1", default-features = false }
spinning_top  = { version = "0.3", default-features = false }

[features]
default = ["worker"]
logging = ["dep:log"]
worker = [] # for dedicated worker. Alse required RUSTFLAGS -Ctarget-feature=+atomics

[profile.release]
panic         = "abort"
lto           = "fat"
strip         = true
opt-level     = "z"
codegen-units = 1
