/// CoC7th で発生しうる判定種別の網羅列挙
/// variant名 = 公式英語名ベース、label = UIに表示する日本語ラベル
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Roll {
    /// Skill Roll — 技能値に対する基本判定（CCコマンド相当）
    SkillRoll,
    /// Characteristic Roll — STR/DEX/POW/LUK等の能力値直接判定
    CharacteristicRoll,
    /// Sanity Roll — 正気度喪失判定
    SanityRoll,
    /// Bout of Madness (Real Time) — 狂気の発作 (リアルタイム)
    BoutOfMadnessRealTime,
    /// Bout of Madness (Summary) — 狂気の発作 (サマリー)
    BoutOfMadnessSummary,
    /// Combined Skill Roll — 2技能を1ロールで同時判定
    CombinedSkillRoll,
    /// Pushed Roll — 失敗後の再挑戦ロール
    PushedRoll,
    /// Automatic Fire Roll — 自動火器の連射判定
    AutoFireRoll,
    /// Failed Casting (Minor) — 呪文失敗表（小）
    FailedCastingMinor,
    /// Failed Casting (Major) — 呪文失敗表（大）
    FailedCastingMajor,
    /// Phobia Table — 恐怖症表
    PhobiaTable,
    /// Mania Table — マニア表
    ManiaTable,
}

impl Roll {
    pub fn label(self) -> &'static str {
        match self {
            Self::SkillRoll              => "技能判定",
            Self::CharacteristicRoll     => "能力値判定",
            Self::SanityRoll             => "正気度判定",
            Self::BoutOfMadnessRealTime  => "狂気の発作 (リアルタイム)",
            Self::BoutOfMadnessSummary   => "狂気の発作 (サマリー)",
            Self::PhobiaTable            => "恐怖症表",
            Self::ManiaTable             => "マニア表",
            Self::CombinedSkillRoll      => "組み合わせ判定",
            Self::PushedRoll             => "プッシュロール",
            Self::AutoFireRoll           => "自動火器の連射判定",
            Self::FailedCastingMinor     => "呪文失敗 (小)",
            Self::FailedCastingMajor     => "呪文失敗 (大)",
        }
    }

    /// UIセレクタ用に全種別を順序付きで返す
    pub fn all() -> &'static [Roll] {
        &[
            Self::SkillRoll,
            Self::CharacteristicRoll,
            Self::SanityRoll,
            Self::BoutOfMadnessRealTime,
            Self::BoutOfMadnessSummary,
            Self::PhobiaTable,
            Self::ManiaTable,
            Self::CombinedSkillRoll,
            Self::PushedRoll,
            Self::AutoFireRoll,
            Self::FailedCastingMinor,
            Self::FailedCastingMajor,
        ]
    }
}

/// ランダム表の1エントリ
#[derive(Debug, Clone, Copy)]
pub struct TableEntry {
    pub id: u32,
    pub keyword: &'static str,
}

/// ルールブック 日本語訳版 153頁
pub static MADNESS_REALTIME_TABLE: [TableEntry; 10] = [
    TableEntry { id: 1, keyword: "健忘症" },
    TableEntry { id: 2, keyword: "身体症状症" },
    TableEntry { id: 3, keyword: "暴力衝動" },
    TableEntry { id: 4, keyword: "偏執症" },
    TableEntry { id: 5, keyword: "重要な人々" },
    TableEntry { id: 6, keyword: "失神" },
    TableEntry { id: 7, keyword: "パニックになって逃亡する" },
    TableEntry { id: 8, keyword: "身体的ヒステリーもしくは感情爆発" },
    TableEntry { id: 9, keyword: "恐怖症" },
    TableEntry { id: 10, keyword: "マニア" },
];

/// ルールブック 日本語訳版 155頁
pub static MADNESS_SUMMARY_TABLE: [TableEntry; 10] = [
    TableEntry { id: 1, keyword: "健忘症" },
    TableEntry { id: 2, keyword: "盗難" },
    TableEntry { id: 3, keyword: "暴行" },
    TableEntry { id: 4, keyword: "暴力" },
    TableEntry { id: 5, keyword: "イデオロギー／信念" },
    TableEntry { id: 6, keyword: "重要な人々" },
    TableEntry { id: 7, keyword: "収容" },
    TableEntry { id: 8, keyword: "パニック" },
    TableEntry { id: 9, keyword: "恐怖症" },
    TableEntry { id: 10, keyword: "マニア" },
];

/// ルールブック 日本語訳版 174頁
pub static FAILED_CASTING_L_TABLE: [TableEntry; 8] = [
    TableEntry { id: 1, keyword: "視界のかすみ、または一時的な失明" },
    TableEntry { id: 2, keyword: "悲鳴、声、雑音が発せられる" },
    TableEntry { id: 3, keyword: "強風などの大気現象" },
    TableEntry { id: 4, keyword: "術者かその場に居合わせた者、あるいは壁などからの出血" },
    TableEntry { id: 5, keyword: "奇妙な幻視と幻覚" },
    TableEntry { id: 6, keyword: "付近の小動物たちが爆発する" },
    TableEntry { id: 7, keyword: "硫黄の悪臭" },
    TableEntry { id: 8, keyword: "クトゥルフ神話の怪物が偶然召喚される" },
];

/// ルールブック 日本語訳版 P175
pub static FAILED_CASTING_M_TABLE: [TableEntry; 8] = [
    TableEntry { id: 1, keyword: "大地が震え、壁に亀裂が入って崩れる" },
    TableEntry { id: 2, keyword: "叙事詩的な電撃" },
    TableEntry { id: 3, keyword: "血が空から降る" },
    TableEntry { id: 4, keyword: "術者の手がしなび、焼けただれる" },
    TableEntry { id: 5, keyword: "術者は不自然に年をとる" },
    TableEntry { id: 6, keyword: "クトゥルフ神話存在が現れ、術者や周囲をに被害を与える" },
    TableEntry { id: 7, keyword: "術者や近くの全員が遠い時代か場所に吸い込まれる" },
    TableEntry { id: 8, keyword: "クトゥルフ神話の神格が偶然招来される" },
];

/// ルールブック 日本語訳版 156頁
pub static PHOBIAS_TABLE: [TableEntry; 100] = [
    TableEntry { id: 1, keyword: "入浴" },
    TableEntry { id: 2, keyword: "高所" },
    TableEntry { id: 3, keyword: "飛行" },
    TableEntry { id: 4, keyword: "広場" },
    TableEntry { id: 5, keyword: "鶏肉" },
    TableEntry { id: 6, keyword: "ニンニク" },
    TableEntry { id: 7, keyword: "乗車" },
    TableEntry { id: 8, keyword: "風" },
    TableEntry { id: 9, keyword: "男性" },
    TableEntry { id: 10, keyword: "イングランド" },
    TableEntry { id: 11, keyword: "花" },
    TableEntry { id: 12, keyword: "切断" },
    TableEntry { id: 13, keyword: "クモ" },
    TableEntry { id: 14, keyword: "稲妻" },
    TableEntry { id: 15, keyword: "廃墟" },
    TableEntry { id: 16, keyword: "笛" },
    TableEntry { id: 17, keyword: "細菌" },
    TableEntry { id: 18, keyword: "銃弾" },
    TableEntry { id: 19, keyword: "落下" },
    TableEntry { id: 20, keyword: "書物" },
    TableEntry { id: 21, keyword: "植物" },
    TableEntry { id: 22, keyword: "美女" },
    TableEntry { id: 23, keyword: "低温" },
    TableEntry { id: 24, keyword: "時計" },
    TableEntry { id: 25, keyword: "閉所" },
    TableEntry { id: 26, keyword: "道化師" },
    TableEntry { id: 27, keyword: "犬" },
    TableEntry { id: 28, keyword: "悪魔" },
    TableEntry { id: 29, keyword: "群集" },
    TableEntry { id: 30, keyword: "歯科医" },
    TableEntry { id: 31, keyword: "処分" },
    TableEntry { id: 32, keyword: "毛皮" },
    TableEntry { id: 33, keyword: "構断" },
    TableEntry { id: 34, keyword: "教会" },
    TableEntry { id: 35, keyword: "鏡" },
    TableEntry { id: 36, keyword: "ピン" },
    TableEntry { id: 37, keyword: "昆虫" },
    TableEntry { id: 38, keyword: "猫" },
    TableEntry { id: 39, keyword: "橋" },
    TableEntry { id: 40, keyword: "老人" },
    TableEntry { id: 41, keyword: "女性" },
    TableEntry { id: 42, keyword: "血液" },
    TableEntry { id: 43, keyword: "過失" },
    TableEntry { id: 44, keyword: "接触" },
    TableEntry { id: 45, keyword: "爬虫類" },
    TableEntry { id: 46, keyword: "霧" },
    TableEntry { id: 47, keyword: "銃器" },
    TableEntry { id: 48, keyword: "水" },
    TableEntry { id: 49, keyword: "睡眠" },
    TableEntry { id: 50, keyword: "医師" },
    TableEntry { id: 51, keyword: "魚" },
    TableEntry { id: 52, keyword: "ゴキブリ" },
    TableEntry { id: 53, keyword: "雷鳴" },
    TableEntry { id: 54, keyword: "野菜" },
    TableEntry { id: 55, keyword: "大騒音" },
    TableEntry { id: 56, keyword: "湖" },
    TableEntry { id: 57, keyword: "機械" },
    TableEntry { id: 58, keyword: "巨大物" },
    TableEntry { id: 59, keyword: "拘束" },
    TableEntry { id: 60, keyword: "隕石" },
    TableEntry { id: 61, keyword: "孤独" },
    TableEntry { id: 62, keyword: "汚染" },
    TableEntry { id: 63, keyword: "粘液" },
    TableEntry { id: 64, keyword: "死体" },
    TableEntry { id: 65, keyword: "8" },
    TableEntry { id: 66, keyword: "歯" },
    TableEntry { id: 67, keyword: "夢" },
    TableEntry { id: 68, keyword: "名称" },
    TableEntry { id: 69, keyword: "蛇" },
    TableEntry { id: 70, keyword: "鳥" },
    TableEntry { id: 71, keyword: "寄生生物" },
    TableEntry { id: 72, keyword: "人形" },
    TableEntry { id: 73, keyword: "恐食症" },
    TableEntry { id: 74, keyword: "薬物" },
    TableEntry { id: 75, keyword: "幽霊" },
    TableEntry { id: 76, keyword: "羞明" },
    TableEntry { id: 77, keyword: "ひげ" },
    TableEntry { id: 78, keyword: "河川" },
    TableEntry { id: 79, keyword: "アルコール" },
    TableEntry { id: 80, keyword: "火" },
    TableEntry { id: 81, keyword: "魔術" },
    TableEntry { id: 82, keyword: "暗黒" },
    TableEntry { id: 83, keyword: "月" },
    TableEntry { id: 84, keyword: "鉄道" },
    TableEntry { id: 85, keyword: "星" },
    TableEntry { id: 86, keyword: "狭所" },
    TableEntry { id: 87, keyword: "対称" },
    TableEntry { id: 88, keyword: "生き埋め" },
    TableEntry { id: 89, keyword: "雄牛" },
    TableEntry { id: 90, keyword: "電話" },
    TableEntry { id: 91, keyword: "奇形" },
    TableEntry { id: 92, keyword: "海洋" },
    TableEntry { id: 93, keyword: "手術" },
    TableEntry { id: 94, keyword: "13" },
    TableEntry { id: 95, keyword: "衣類" },
    TableEntry { id: 96, keyword: "魔女" },
    TableEntry { id: 97, keyword: "黄色" },
    TableEntry { id: 98, keyword: "外国語" },
    TableEntry { id: 99, keyword: "外国人" },
    TableEntry { id: 100, keyword: "動物" },
];

/// ルールブック 日本語訳版 157頁
pub static MANIAS_TABLE: [TableEntry; 100] = [
    TableEntry { id: 1, keyword: "洗浄" },
    TableEntry { id: 2, keyword: "無為" },
    TableEntry { id: 3, keyword: "暗闇" },
    TableEntry { id: 4, keyword: "高所" },
    TableEntry { id: 5, keyword: "善良" },
    TableEntry { id: 6, keyword: "広場" },
    TableEntry { id: 7, keyword: "先鋭" },
    TableEntry { id: 8, keyword: "猫" },
    TableEntry { id: 9, keyword: "疼痛性愛" },
    TableEntry { id: 10, keyword: "にんにく" },
    TableEntry { id: 11, keyword: "乗り物" },
    TableEntry { id: 12, keyword: "病的快活" },
    TableEntry { id: 13, keyword: "花" },
    TableEntry { id: 14, keyword: "計算" },
    TableEntry { id: 15, keyword: "浪費" },
    TableEntry { id: 16, keyword: "自己" },
    TableEntry { id: 17, keyword: "バレエ" },
    TableEntry { id: 18, keyword: "書籍約盗癖" },
    TableEntry { id: 19, keyword: "書物" },
    TableEntry { id: 20, keyword: "歯ぎしり" },
    TableEntry { id: 21, keyword: "悪霊" },
    TableEntry { id: 22, keyword: "自己愛" },
    TableEntry { id: 23, keyword: "地図" },
    TableEntry { id: 24, keyword: "飛び降り" },
    TableEntry { id: 25, keyword: "寒冷" },
    TableEntry { id: 26, keyword: "舞踏" },
    TableEntry { id: 27, keyword: "睡眠" },
    TableEntry { id: 28, keyword: "墓地" },
    TableEntry { id: 29, keyword: "色彩" },
    TableEntry { id: 30, keyword: "ピエロ" },
    TableEntry { id: 31, keyword: "遭遇" },
    TableEntry { id: 32, keyword: "殺害" },
    TableEntry { id: 33, keyword: "悪魔" },
    TableEntry { id: 34, keyword: "皮膚" },
    TableEntry { id: 35, keyword: "正義" },
    TableEntry { id: 36, keyword: "アルコール" },
    TableEntry { id: 37, keyword: "毛皮" },
    TableEntry { id: 38, keyword: "贈り物" },
    TableEntry { id: 39, keyword: "逃走" },
    TableEntry { id: 40, keyword: "外出" },
    TableEntry { id: 41, keyword: "自己中心" },
    TableEntry { id: 42, keyword: "公職" },
    TableEntry { id: 43, keyword: "戦慄" },
    TableEntry { id: 44, keyword: "知識" },
    TableEntry { id: 45, keyword: "静寂" },
    TableEntry { id: 46, keyword: "エーテル" },
    TableEntry { id: 47, keyword: "求婚" },
    TableEntry { id: 48, keyword: "笑い" },
    TableEntry { id: 49, keyword: "魔術" },
    TableEntry { id: 50, keyword: "筆記" },
    TableEntry { id: 51, keyword: "裸体" },
    TableEntry { id: 52, keyword: "幻想" },
    TableEntry { id: 53, keyword: "蟲" },
    TableEntry { id: 54, keyword: "火器" },
    TableEntry { id: 55, keyword: "水" },
    TableEntry { id: 56, keyword: "魚" },
    TableEntry { id: 57, keyword: "アイコン" },
    TableEntry { id: 58, keyword: "アイドル" },
    TableEntry { id: 59, keyword: "情報" },
    TableEntry { id: 60, keyword: "絶叫" },
    TableEntry { id: 61, keyword: "窃盗" },
    TableEntry { id: 62, keyword: "騒音" },
    TableEntry { id: 63, keyword: "ひも" },
    TableEntry { id: 64, keyword: "宝くじ" },
    TableEntry { id: 65, keyword: "うつ" },
    TableEntry { id: 66, keyword: "巨石" },
    TableEntry { id: 67, keyword: "音楽" },
    TableEntry { id: 68, keyword: "作詩" },
    TableEntry { id: 69, keyword: "憎悪" },
    TableEntry { id: 70, keyword: "偏執" },
    TableEntry { id: 71, keyword: "虚言" },
    TableEntry { id: 72, keyword: "疾病" },
    TableEntry { id: 73, keyword: "記録" },
    TableEntry { id: 74, keyword: "名前" },
    TableEntry { id: 75, keyword: "単語" },
    TableEntry { id: 76, keyword: "爪損傷" },
    TableEntry { id: 77, keyword: "美食" },
    TableEntry { id: 78, keyword: "不平" },
    TableEntry { id: 79, keyword: "仮面" },
    TableEntry { id: 80, keyword: "幽霊" },
    TableEntry { id: 81, keyword: "殺人" },
    TableEntry { id: 82, keyword: "光線" },
    TableEntry { id: 83, keyword: "放浪" },
    TableEntry { id: 84, keyword: "長者" },
    TableEntry { id: 85, keyword: "病的虚言" },
    TableEntry { id: 86, keyword: "放火" },
    TableEntry { id: 87, keyword: "質問" },
    TableEntry { id: 88, keyword: "鼻" },
    TableEntry { id: 89, keyword: "落書き" },
    TableEntry { id: 90, keyword: "列車" },
    TableEntry { id: 91, keyword: "知性" },
    TableEntry { id: 92, keyword: "テクノ" },
    TableEntry { id: 93, keyword: "タナトス" },
    TableEntry { id: 94, keyword: "宗教" },
    TableEntry { id: 95, keyword: "かき傷" },
    TableEntry { id: 96, keyword: "手術" },
    TableEntry { id: 97, keyword: "抜毛" },
    TableEntry { id: 98, keyword: "失明" },
    TableEntry { id: 99, keyword: "異国" },
    TableEntry { id: 100, keyword: "動物" },
];
