use crate::Lang;
use crate::character,

pub enum Roll { 
    DiceRoll,
    SkillRoll,
    CharacteristicRoll,
    // todo: SkillRollとChracteristicRollへの難易度指定セレクタ追加 (これによりRollJudgeが成功/失敗の二値表現に変わる)
    SanityRoll,
    BoutOfMadnessRealTime,
    BoutOfMadnessSummary,
    PushedRoll,
    CombinedSkillRoll,
    PhobiaTable,
    ManiaTable,
    // todo: 射撃時の連射判定, 射撃時のボーナス・ペナルティダイスのセレクタガイド
    AutoFireRoll,
    FailedCastingMinor,
    FailedCastingMajor,
    DevelopmentCheck,
}

pub struct DiceRoll {
    character:   character::Instance,
    roll_select:   Roll,
    select: Vec<DiceRollSelect>,
    target_select: (character::Schema::Characteristic,character::Schema::Skill),
    input_counts: u16,
    input_sides: [2, 3, 4, 5, 6, 8, 10, 12, 20, 100];
    input_modifier: i16,
    result: RollResult,
}

pub struct RollResult {
    roll_total: Vec<i16>,
    roll_judge: Option(Vev<RollJudge>),
}

pub enum RollJudge {
    Famble,
    Failure,
    Regular,
    Hard,
    Extreme,
    Critical,
    Sane,
    Insane,
    Developed,
    Undeveloped,
}

impl RollJudge {
    pub fn label(self, lang: Lang) -> &'static str {
        match(self, lang) {
            (Self::Famble,      Lang::En) => "famble",
            (Self::Famble,      Lang::Ja) => "致命的失敗",
            (Self::Failure,     Lang::En) => "failure",
            (Self::Failure,     Lang::Ja) => "失敗",
            (Self::Regular,     Lang::En) => "regular success",
            (Self::Regular,     Lang::Ja) => "レギュラー成功",
            (Self::Hard,        Lang::En) => "hard success",
            (Self::Hard,        Lang::Ja) => "ハード成功",
            (Self::Extreme,     Lang::En) => "extreme success",
            (Self::Extreme,     Lang::Ja) => "イクストリーム成功",  
            (Self::Ctirical,    Lang::En) => "critical success",
            (Self::Critical,    Lang::Ja) => "クリティカル成功",  
            (Self::Sane,        Lang::En) => "stay sane",
            (Self::Sane,        Lang::Ja) => "発狂しない",  
            (Self::Insane,      Lang::En) => "go insane",
            (Self::Insane,      Lang::Ja) => "発狂",  
            (Self::Developed,   Lang::En) => "developed",
            (Self::Developed,   Lang::Ja) => "上達",
            (Self::Undeveloped, Lang::En) => "undeveloped",
            (Self::Undeveloped, Lang::Ja) => "上達しない",                                            
        }
    }
}

impl Roll {
    pub fn label(self, lang: Lang) -> &'static str {
        match (self, lang) {
            (Self::DiceRoll,              Lang::Ja) => "ダイスロール (nDn +-n)",
            (Self::DiceRoll,              Lang::En) => "Dice Roll (nDn +-n)",
            (Self::SkillRoll,             Lang::Ja) => "技能判定",
            (Self::SkillRoll,             Lang::En) => "Skill Roll",
            (Self::CharacteristicRoll,    Lang::Ja) => "能力値判定 (幸運含む)",
            (Self::CharacteristicRoll,    Lang::En) => "Characteristic Roll",
            (Self::SanityRoll,            Lang::Ja) => "正気度判定",
            (Self::SanityRoll,            Lang::En) => "Sanity Roll",
            (Self::BoutOfMadnessRealTime, Lang::Ja) => "狂気の発作 (リアルタイム)",
            (Self::BoutOfMadnessRealTime, Lang::En) => "Bout of Madness (Real Time)",
            (Self::BoutOfMadnessSummary,  Lang::Ja) => "狂気の発作 (サマリー)",
            (Self::BoutOfMadnessSummary,  Lang::En) => "Bout of Madness (Summary)",
            (Self::PushedRoll,            Lang::Ja) => "プッシュロール",
            (Self::PushedRoll,            Lang::En) => "Pushed Roll",
            (Self::CombinedSkillRoll,     Lang::Ja) => "組み合わせ判定",
            (Self::CombinedSkillRoll,     Lang::En) => "Combined Skill Roll",
            (Self::PhobiaTable,           Lang::Ja) => "恐怖症表",
            (Self::PhobiaTable,           Lang::En) => "Phobia Table",
            (Self::ManiaTable,            Lang::Ja) => "マニア表",
            (Self::ManiaTable,            Lang::En) => "Mania Table",
            (Self::AutoFireRoll,          Lang::Ja) => "自動火器の連射判定",
            (Self::AutoFireRoll,          Lang::En) => "Automatic Fire Roll",
            (Self::FailedCastingMinor,    Lang::Ja) => "呪文失敗 (小)",
            (Self::FailedCastingMinor,    Lang::En) => "Failed Casting (Minor)",
            (Self::FailedCastingMajor,    Lang::Ja) => "呪文失敗 (大)",
            (Self::FailedCastingMajor,    Lang::En) => "Failed Casting (Major)",
            (Self::DevelopmentCheck,      Lang::En) => "Development Check",
            (Self::DevelopmentCheck,      Lang::Ja) => "上達チェック",
        }
    }

    pub fn all() -> &'static [Roll] {
        &[
            Self::DiceRoll,
            Self::SkillRoll,
            Self::CharacteristicRoll,
            Self::SanityRoll,
            Self::BoutOfMadnessRealTime,
            Self::BoutOfMadnessSummary,
            Self::PushedRoll,
            Self::CombinedSkillRoll,
            Self::PhobiaTable,
            Self::ManiaTable,
            Self::AutoFireRoll,
            Self::FailedCastingMinor,
            Self::FailedCastingMajor,
            Self::DevelopmentCheck,
        ]
    }
}


/// ルールブック 日本語訳版 153頁
pub enum MadnessRealTime {
    Amnesia,
    PsychosomaticDisability,
    Violence,
    Paranoia,
    SignificantPerson,
    Faint,
    FleeInPanic,
    PhysicalHysterics,
    Phobia,
    Mania,
}

impl MadnessRealTime {
    pub fn label(&self, lang: Lang) -> &'static str {
        match (self, lang) {
            (Self::Amnesia,                Lang::En) => "Amnesia",
            (Self::Amnesia,                Lang::Ja) => "健忘症",
            (Self::PsychosomaticDisability,Lang::En) => "Psychosomatic Disability",
            (Self::PsychosomaticDisability,Lang::Ja) => "身体症状症",
            (Self::Violence,               Lang::En) => "Violence",
            (Self::Violence,               Lang::Ja) => "暴力衝動",
            (Self::Paranoia,               Lang::En) => "Paranoia",
            (Self::Paranoia,               Lang::Ja) => "偏執症",
            (Self::SignificantPerson,      Lang::En) => "Significant Person",
            (Self::SignificantPerson,      Lang::Ja) => "重要な人々",
            (Self::Faint,                  Lang::En) => "Faint",
            (Self::Faint,                  Lang::Ja) => "失神",
            (Self::FleeInPanic,            Lang::En) => "Flee in Panic",
            (Self::FleeInPanic,            Lang::Ja) => "パニックになって逃亡する",
            (Self::PhysicalHysterics,      Lang::En) => "Physical Hysterics or Emotional Outburst",
            (Self::PhysicalHysterics,      Lang::Ja) => "身体的ヒステリーもしくは感情爆発",
            (Self::Phobia,                 Lang::En) => "Phobia",
            (Self::Phobia,                 Lang::Ja) => "恐怖症",
            (Self::Mania,                  Lang::En) => "Mania",
            (Self::Mania,                  Lang::Ja) => "マニア",
        }
    }

    pub fn all() -> &'static [Self] {
        &[
            Self::Amnesia,
            Self::PsychosomaticDisability,
            Self::Violence,
            Self::Paranoia,
            Self::SignificantPerson,
            Self::Faint,
            Self::FleeInPanic,
            Self::PhysicalHysterics,
            Self::Phobia,
            Self::Mania,
        ]
    }
}

/// ルールブック 日本語訳版 155頁
pub enum MadnessSummary {
    Amnesia,
    Robbed,
    Battered,
    Violence,
    IdeologyBeliefs,
    SignificantPeople,
    Institutionalized,
    FleeInPanic,
    Phobia,
    Mania,
}

impl MadnessSummary {
    pub fn label(&self, lang: Lang) -> &'static str {
        match (self, lang) {
            (Self::Amnesia,          Lang::En) => "Amnesia",
            (Self::Amnesia,          Lang::Ja) => "健忘症",
            (Self::Robbed,           Lang::En) => "Robbed",
            (Self::Robbed,           Lang::Ja) => "盗難",
            (Self::Battered,         Lang::En) => "Battered",
            (Self::Battered,         Lang::Ja) => "暴行",
            (Self::Violence,         Lang::En) => "Violence",
            (Self::Violence,         Lang::Ja) => "暴力",
            (Self::IdeologyBeliefs,  Lang::En) => "Ideology/Beliefs",
            (Self::IdeologyBeliefs,  Lang::Ja) => "イデオロギー／信念",
            (Self::SignificantPeople,Lang::En) => "Significant People",
            (Self::SignificantPeople,Lang::Ja) => "重要な人々",
            (Self::Institutionalized,Lang::En) => "Institutionalized",
            (Self::Institutionalized,Lang::Ja) => "収容",
            (Self::FleeInPanic,      Lang::En) => "Flee in Panic",
            (Self::FleeInPanic,      Lang::Ja) => "パニック",
            (Self::Phobia,           Lang::En) => "Phobia",
            (Self::Phobia,           Lang::Ja) => "恐怖症",
            (Self::Mania,            Lang::En) => "Mania",
            (Self::Mania,            Lang::Ja) => "マニア",
        }
    }

    pub fn all() -> &'static [Self] {
        &[
            Self::Amnesia,
            Self::Robbed,
            Self::Battered,
            Self::Violence,
            Self::IdeologyBeliefs,
            Self::SignificantPeople,
            Self::Institutionalized,
            Self::FleeInPanic,
            Self::Phobia,
            Self::Mania,
        ]
    }
}

/// ルールブック 日本語訳版 174頁
pub enum FailedCastingMinor {
    BlurredVision,
    Screaming,
    StrongWind,
    Bleeding,
    StrangeVisions,
    SmallAnimalsExplode,
    StenchOfSulphur,
    MythosCreatureSummoned,
}

impl FailedCastingMinor {
    pub fn label(&self, lang: Lang) -> &'static str {
        match (self, lang) {
            (Self::BlurredVision,          Lang::En) => "Blurred vision or temporary blindness",
            (Self::BlurredVision,          Lang::Ja) => "視界のかすみ、または一時的な失明",
            (Self::Screaming,              Lang::En) => "Screaming, voices, or other noises",
            (Self::Screaming,              Lang::Ja) => "悲鳴、声、雑音が発せられる",
            (Self::StrongWind,             Lang::En) => "Strong winds or other atmospheric effects",
            (Self::StrongWind,             Lang::Ja) => "強風などの大気現象",
            (Self::Bleeding,               Lang::En) => "Bleeding from the caster, bystanders, or environment",
            (Self::Bleeding,               Lang::Ja) => "術者かその場に居合わせた者、あるいは壁などからの出血",
            (Self::StrangeVisions,         Lang::En) => "Strange visions and hallucinations",
            (Self::StrangeVisions,         Lang::Ja) => "奇妙な幻視と幻覚",
            (Self::SmallAnimalsExplode,    Lang::En) => "Nearby small animals explode",
            (Self::SmallAnimalsExplode,    Lang::Ja) => "付近の小動物たちが爆発する",
            (Self::StenchOfSulphur,        Lang::En) => "Foul stench of sulphur",
            (Self::StenchOfSulphur,        Lang::Ja) => "硫黄の悪臭",
            (Self::MythosCreatureSummoned, Lang::En) => "A Mythos creature is accidentally summoned",
            (Self::MythosCreatureSummoned, Lang::Ja) => "クトゥルフ神話の怪物が偶然召喚される",
        }
    }

    pub fn all() -> &'static [Self] {
        &[
            Self::BlurredVision,
            Self::Screaming,
            Self::StrongWind,
            Self::Bleeding,
            Self::StrangeVisions,
            Self::SmallAnimalsExplode,
            Self::StenchOfSulphur,
            Self::MythosCreatureSummoned,
        ]
    }
}

/// ルールブック 日本語訳版 P175
pub enum FailedCastingMajor {
    Earthquake,
    EpicLightning,
    BloodRain,
    CasterHandsWither,
    CasterAgesUnaturally,
    MythosCreatureAttacks,
    SweptAwayInTime,
    MythosDeityInvoked,
}

impl FailedCastingMajor {
    pub fn label(&self, lang: Lang) -> &'static str {
        match (self, lang) {
            (Self::Earthquake,           Lang::En) => "The earth shakes and walls crack and crumble",
            (Self::Earthquake,           Lang::Ja) => "大地が震え、壁に亀裂が入って崩れる",
            (Self::EpicLightning,        Lang::En) => "Epic lightning strike",
            (Self::EpicLightning,        Lang::Ja) => "叙事詩的な電撃",
            (Self::BloodRain,            Lang::En) => "Blood rains from the sky",
            (Self::BloodRain,            Lang::Ja) => "血が空から降る",
            (Self::CasterHandsWither,    Lang::En) => "The caster's hands wither and are seared",
            (Self::CasterHandsWither,    Lang::Ja) => "術者の手がしなび、焼けただれる",
            (Self::CasterAgesUnaturally, Lang::En) => "The caster ages unnaturally",
            (Self::CasterAgesUnaturally, Lang::Ja) => "術者は不自然に年をとる",
            (Self::MythosCreatureAttacks,Lang::En) => "A Mythos creature appears and attacks those nearby",
            (Self::MythosCreatureAttacks,Lang::Ja) => "クトゥルフ神話存在が現れ、術者や周囲をに被害を与える",
            (Self::SweptAwayInTime,      Lang::En) => "The caster and all nearby are swept away to a distant time or place",
            (Self::SweptAwayInTime,      Lang::Ja) => "術者や近くの全員が遠い時代か場所に吸い込まれる",
            (Self::MythosDeityInvoked,   Lang::En) => "A Mythos deity is accidentally invoked",
            (Self::MythosDeityInvoked,   Lang::Ja) => "クトゥルフ神話の神格が偶然招来される",
        }
    }

    pub fn all() -> &'static [Self] {
        &[
            Self::Earthquake,
            Self::EpicLightning,
            Self::BloodRain,
            Self::CasterHandsWither,
            Self::CasterAgesUnaturally,
            Self::MythosCreatureAttacks,
            Self::SweptAwayInTime,
            Self::MythosDeityInvoked,
        ]
    }
}

/// ルールブック 日本語訳版 156頁
pub enum Phobia {
    Ablutophobia,
    Acrophobia,
    Aerophobia,
    Agoraphobia,
    Alektorophobia,
    Alliumphobia,
    Amaxophobia,
    Ancraophobia,
    Androphobia,
    Anglophobia,
    Anthophobia,
    Apotemnophobia,
    Arachnophobia,
    Astraphobia,
    Atephobia,
    Aulophobia,
    Bacteriophobia,
    Ballistophobia,
    Basophobia,
    Bibliophobia,
    Botanophobia,
    Caligynephobia,
    Cheimaphobia,
    Chronomentrophobia,
    Claustrophobia,
    Coulrophobia,
    Cynophobia,
    Demonophobia,
    Demophobia,
    Dentophobia,
    Disposophobia,
    Doraphobia,
    Dromophobia,
    Ecclesiophobia,
    Eisoptrophobia,
    Enetophobia,
    Entomophobia,
    Felinophobia,
    Gephyrophobia,
    Gerontophobia,
    Gynophobia,
    Haemaphobia,
    Hamartophobia,
    Haphophobia,
    Herpetophobia,
    Homichlophobia,
    Hoplophobia,
    Hydrophobia,
    Hypnophobia,
    Iatrophobia,
    Ichthyophobia,
    Katsaridaphobia,
    Keraunophobia,
    Lachanophobia,
    Ligyrophobia,
    Limnophobia,
    Mechanophobia,
    Megalophobia,
    Merinthophobia,
    Meteorophobia,
    Monophobia,
    Mysophobia,
    Myxophobia,
    Necrophobia,
    Octophobia,
    Odontophobia,
    Oneirophobia,
    Onomatophobia,
    Ophidiophobia,
    Ornithophobia,
    Parasitophobia,
    Pediophobia,
    Phagophobia,
    Pharmacophobia,
    Phasmophobia,
    Phenogophobia,
    Pogonophobia,
    Potamophobia,
    Potophobia,
    Pyrophobia,
    Rhabdophobia,
    Scotophobia,
    Selenophobia,
    Siderodromophobia,
    Siderophobia,
    Stenophobia,
    Symmetrophobia,
    Taphephobia,
    Taurophobia,
    Telephonophobia,
    Teratophobia,
    Thalassophobia,
    Tomophobia,
    Triskadekaphobia,
    Vestiphobia,
    Wiccaphobia,
    Xanthophobia,
    Xenoglossophobia,
    Xenophobia,
    Zoophobia,
}

impl Phobia {
    pub fn label(&self, lang: Lang) -> &'static str {
        match (self, lang) {
            (Self::Ablutophobia,       Lang::En) => "Ablutophobia",
            (Self::Ablutophobia,       Lang::Ja) => "入浴恐怖症",
            (Self::Acrophobia,         Lang::En) => "Acrophobia",
            (Self::Acrophobia,         Lang::Ja) => "高所恐怖症",
            (Self::Aerophobia,         Lang::En) => "Aerophobia",
            (Self::Aerophobia,         Lang::Ja) => "飛行恐怖症",
            (Self::Agoraphobia,        Lang::En) => "Agoraphobia",
            (Self::Agoraphobia,        Lang::Ja) => "広場恐怖症",
            (Self::Alektorophobia,     Lang::En) => "Alektorophobia",
            (Self::Alektorophobia,     Lang::Ja) => "恐鶏症",
            (Self::Alliumphobia,       Lang::En) => "Alliumphobia",
            (Self::Alliumphobia,       Lang::Ja) => "大蒜恐怖症",
            (Self::Amaxophobia,        Lang::En) => "Amaxophobia",
            (Self::Amaxophobia,        Lang::Ja) => "乗車恐怖症",
            (Self::Ancraophobia,       Lang::En) => "Ancraophobia",
            (Self::Ancraophobia,       Lang::Ja) => "恐風症",
            (Self::Androphobia,        Lang::En) => "Androphobia",
            (Self::Androphobia,        Lang::Ja) => "男性恐怖症",
            (Self::Anglophobia,        Lang::En) => "Anglophobia",
            (Self::Anglophobia,        Lang::Ja) => "恐英症",
            (Self::Anthophobia,        Lang::En) => "Anthophobia",
            (Self::Anthophobia,        Lang::Ja) => "恐花症",
            (Self::Apotemnophobia,     Lang::En) => "Apotemnophobia",
            (Self::Apotemnophobia,     Lang::Ja) => "截肢者恐怖症",
            (Self::Arachnophobia,      Lang::En) => "Arachnophobia",
            (Self::Arachnophobia,      Lang::Ja) => "蜘蛛恐怖症",
            (Self::Astraphobia,        Lang::En) => "Astraphobia",
            (Self::Astraphobia,        Lang::Ja) => "閃電恐怖症",
            (Self::Atephobia,          Lang::En) => "Atephobia",
            (Self::Atephobia,          Lang::Ja) => "廃墟恐怖症",
            (Self::Aulophobia,         Lang::En) => "Aulophobia",
            (Self::Aulophobia,         Lang::Ja) => "長笛恐怖症",
            (Self::Bacteriophobia,     Lang::En) => "Bacteriophobia",
            (Self::Bacteriophobia,     Lang::Ja) => "細菌恐怖症",
            (Self::Ballistophobia,     Lang::En) => "Ballistophobia",
            (Self::Ballistophobia,     Lang::Ja) => "銃弾恐怖症",
            (Self::Basophobia,         Lang::En) => "Basophobia",
            (Self::Basophobia,         Lang::Ja) => "落下恐怖症",
            (Self::Bibliophobia,       Lang::En) => "Bibliophobia",
            (Self::Bibliophobia,       Lang::Ja) => "書籍恐怖症",
            (Self::Botanophobia,       Lang::En) => "Botanophobia",
            (Self::Botanophobia,       Lang::Ja) => "植物恐怖症",
            (Self::Caligynephobia,     Lang::En) => "Caligynephobia",
            (Self::Caligynephobia,     Lang::Ja) => "美女恐怖症",
            (Self::Cheimaphobia,       Lang::En) => "Cheimaphobia",
            (Self::Cheimaphobia,       Lang::Ja) => "寒冷恐怖症",
            (Self::Chronomentrophobia, Lang::En) => "Chronomentrophobia",
            (Self::Chronomentrophobia, Lang::Ja) => "時計恐怖症",
            (Self::Claustrophobia,     Lang::En) => "Claustrophobia",
            (Self::Claustrophobia,     Lang::Ja) => "閉所恐怖症",
            (Self::Coulrophobia,       Lang::En) => "Coulrophobia",
            (Self::Coulrophobia,       Lang::Ja) => "道化師恐怖症",
            (Self::Cynophobia,         Lang::En) => "Cynophobia",
            (Self::Cynophobia,         Lang::Ja) => "恐犬症",
            (Self::Demonophobia,       Lang::En) => "Demonophobia",
            (Self::Demonophobia,       Lang::Ja) => "悪魔恐怖症",
            (Self::Demophobia,         Lang::En) => "Demophobia",
            (Self::Demophobia,         Lang::Ja) => "群衆恐怖症",
            (Self::Dentophobia,        Lang::En) => "Dentophobia",
            (Self::Dentophobia,        Lang::Ja) => "歯科恐怖症",
            (Self::Disposophobia,      Lang::En) => "Disposophobia",
            (Self::Disposophobia,      Lang::Ja) => "処分恐怖症",
            (Self::Doraphobia,         Lang::En) => "Doraphobia",
            (Self::Doraphobia,         Lang::Ja) => "毛皮恐怖症",
            (Self::Dromophobia,        Lang::En) => "Dromophobia",
            (Self::Dromophobia,        Lang::Ja) => "横断恐怖症",
            (Self::Ecclesiophobia,     Lang::En) => "Ecclesiophobia",
            (Self::Ecclesiophobia,     Lang::Ja) => "教会恐怖症",
            (Self::Eisoptrophobia,     Lang::En) => "Eisoptrophobia",
            (Self::Eisoptrophobia,     Lang::Ja) => "鏡恐怖症",
            (Self::Enetophobia,        Lang::En) => "Enetophobia",
            (Self::Enetophobia,        Lang::Ja) => "針恐怖症",
            (Self::Entomophobia,       Lang::En) => "Entomophobia",
            (Self::Entomophobia,       Lang::Ja) => "昆虫恐怖症",
            (Self::Felinophobia,       Lang::En) => "Felinophobia",
            (Self::Felinophobia,       Lang::Ja) => "恐猫症",
            (Self::Gephyrophobia,      Lang::En) => "Gephyrophobia",
            (Self::Gephyrophobia,      Lang::Ja) => "橋恐怖症",
            (Self::Gerontophobia,      Lang::En) => "Gerontophobia",
            (Self::Gerontophobia,      Lang::Ja) => "老人恐怖症",
            (Self::Gynophobia,         Lang::En) => "Gynophobia",
            (Self::Gynophobia,         Lang::Ja) => "女性恐怖症",
            (Self::Haemaphobia,        Lang::En) => "Haemaphobia",
            (Self::Haemaphobia,        Lang::Ja) => "血液恐怖症",
            (Self::Hamartophobia,      Lang::En) => "Hamartophobia",
            (Self::Hamartophobia,      Lang::Ja) => "宗教罪行恐怖症",
            (Self::Haphophobia,        Lang::En) => "Haphophobia",
            (Self::Haphophobia,        Lang::Ja) => "接触恐怖症",
            (Self::Herpetophobia,      Lang::En) => "Herpetophobia",
            (Self::Herpetophobia,      Lang::Ja) => "爬虫類恐怖症",
            (Self::Homichlophobia,     Lang::En) => "Homichlophobia",
            (Self::Homichlophobia,     Lang::Ja) => "霧恐怖症",
            (Self::Hoplophobia,        Lang::En) => "Hoplophobia",
            (Self::Hoplophobia,        Lang::Ja) => "銃器恐怖症",
            (Self::Hydrophobia,        Lang::En) => "Hydrophobia",
            (Self::Hydrophobia,        Lang::Ja) => "恐水症",
            (Self::Hypnophobia,        Lang::En) => "Hypnophobia",
            (Self::Hypnophobia,        Lang::Ja) => "睡眠恐怖症",
            (Self::Iatrophobia,        Lang::En) => "Iatrophobia",
            (Self::Iatrophobia,        Lang::Ja) => "医師恐怖症",
            (Self::Ichthyophobia,      Lang::En) => "Ichthyophobia",
            (Self::Ichthyophobia,      Lang::Ja) => "魚類恐怖症",
            (Self::Katsaridaphobia,    Lang::En) => "Katsaridaphobia",
            (Self::Katsaridaphobia,    Lang::Ja) => "蟑螂恐怖症",
            (Self::Keraunophobia,      Lang::En) => "Keraunophobia",
            (Self::Keraunophobia,      Lang::Ja) => "雷鳴恐怖症",
            (Self::Lachanophobia,      Lang::En) => "Lachanophobia",
            (Self::Lachanophobia,      Lang::Ja) => "野菜恐怖症",
            (Self::Ligyrophobia,       Lang::En) => "Ligyrophobia",
            (Self::Ligyrophobia,       Lang::Ja) => "騒音恐怖症",
            (Self::Limnophobia,        Lang::En) => "Limnophobia",
            (Self::Limnophobia,        Lang::Ja) => "湖恐怖症",
            (Self::Mechanophobia,      Lang::En) => "Mechanophobia",
            (Self::Mechanophobia,      Lang::Ja) => "機械恐怖症",
            (Self::Megalophobia,       Lang::En) => "Megalophobia",
            (Self::Megalophobia,       Lang::Ja) => "巨大物恐怖症",
            (Self::Merinthophobia,     Lang::En) => "Merinthophobia",
            (Self::Merinthophobia,     Lang::Ja) => "拘束恐怖症",
            (Self::Meteorophobia,      Lang::En) => "Meteorophobia",
            (Self::Meteorophobia,      Lang::Ja) => "流星恐怖症",
            (Self::Monophobia,         Lang::En) => "Monophobia",
            (Self::Monophobia,         Lang::Ja) => "孤独恐怖症",
            (Self::Mysophobia,         Lang::En) => "Mysophobia",
            (Self::Mysophobia,         Lang::Ja) => "不潔恐怖症",
            (Self::Myxophobia,         Lang::En) => "Myxophobia",
            (Self::Myxophobia,         Lang::Ja) => "粘液恐怖症",
            (Self::Necrophobia,        Lang::En) => "Necrophobia",
            (Self::Necrophobia,        Lang::Ja) => "屍体恐怖症",
            (Self::Octophobia,         Lang::En) => "Octophobia",
            (Self::Octophobia,         Lang::Ja) => "数字8恐怖症",
            (Self::Odontophobia,       Lang::En) => "Odontophobia",
            (Self::Odontophobia,       Lang::Ja) => "歯恐怖症",
            (Self::Oneirophobia,       Lang::En) => "Oneirophobia",
            (Self::Oneirophobia,       Lang::Ja) => "夢恐怖症",
            (Self::Onomatophobia,      Lang::En) => "Onomatophobia",
            (Self::Onomatophobia,      Lang::Ja) => "名称恐怖症",
            (Self::Ophidiophobia,      Lang::En) => "Ophidiophobia",
            (Self::Ophidiophobia,      Lang::Ja) => "蛇恐怖症",
            (Self::Ornithophobia,      Lang::En) => "Ornithophobia",
            (Self::Ornithophobia,      Lang::Ja) => "鳥恐怖症",
            (Self::Parasitophobia,     Lang::En) => "Parasitophobia",
            (Self::Parasitophobia,     Lang::Ja) => "寄生虫恐怖症",
            (Self::Pediophobia,        Lang::En) => "Pediophobia",
            (Self::Pediophobia,        Lang::Ja) => "人形恐怖症",
            (Self::Phagophobia,        Lang::En) => "Phagophobia",
            (Self::Phagophobia,        Lang::Ja) => "嚥下恐怖症",
            (Self::Pharmacophobia,     Lang::En) => "Pharmacophobia",
            (Self::Pharmacophobia,     Lang::Ja) => "薬物恐怖症",
            (Self::Phasmophobia,       Lang::En) => "Phasmophobia",
            (Self::Phasmophobia,       Lang::Ja) => "幽霊恐怖症",
            (Self::Phenogophobia,      Lang::En) => "Phenogophobia",
            (Self::Phenogophobia,      Lang::Ja) => "日光恐怖症",
            (Self::Pogonophobia,       Lang::En) => "Pogonophobia",
            (Self::Pogonophobia,       Lang::Ja) => "髭恐怖症",
            (Self::Potamophobia,       Lang::En) => "Potamophobia",
            (Self::Potamophobia,       Lang::Ja) => "河川恐怖症",
            (Self::Potophobia,         Lang::En) => "Potophobia",
            (Self::Potophobia,         Lang::Ja) => "飲酒恐怖症",
            (Self::Pyrophobia,         Lang::En) => "Pyrophobia",
            (Self::Pyrophobia,         Lang::Ja) => "恐火症",
            (Self::Rhabdophobia,       Lang::En) => "Rhabdophobia",
            (Self::Rhabdophobia,       Lang::Ja) => "魔術恐怖症",
            (Self::Scotophobia,        Lang::En) => "Scotophobia",
            (Self::Scotophobia,        Lang::Ja) => "暗黒恐怖症",
            (Self::Selenophobia,       Lang::En) => "Selenophobia",
            (Self::Selenophobia,       Lang::Ja) => "月恐怖症",
            (Self::Siderodromophobia,  Lang::En) => "Siderodromophobia",
            (Self::Siderodromophobia,  Lang::Ja) => "鉄道恐怖症",
            (Self::Siderophobia,       Lang::En) => "Siderophobia",
            (Self::Siderophobia,       Lang::Ja) => "星恐怖症",
            (Self::Stenophobia,        Lang::En) => "Stenophobia",
            (Self::Stenophobia,        Lang::Ja) => "狭所恐怖症",
            (Self::Symmetrophobia,     Lang::En) => "Symmetrophobia",
            (Self::Symmetrophobia,     Lang::Ja) => "対称恐怖症",
            (Self::Taphephobia,        Lang::En) => "Taphephobia",
            (Self::Taphephobia,        Lang::Ja) => "生き埋め恐怖症",
            (Self::Taurophobia,        Lang::En) => "Taurophobia",
            (Self::Taurophobia,        Lang::Ja) => "雄牛恐怖症",
            (Self::Telephonophobia,    Lang::En) => "Telephonophobia",
            (Self::Telephonophobia,    Lang::Ja) => "電話恐怖症",
            (Self::Teratophobia,       Lang::En) => "Teratophobia",
            (Self::Teratophobia,       Lang::Ja) => "奇形恐怖症",
            (Self::Thalassophobia,     Lang::En) => "Thalassophobia",
            (Self::Thalassophobia,     Lang::Ja) => "海洋恐怖症",
            (Self::Tomophobia,         Lang::En) => "Tomophobia",
            (Self::Tomophobia,         Lang::Ja) => "手術恐怖症",
            (Self::Triskadekaphobia,   Lang::En) => "Triskadekaphobia",
            (Self::Triskadekaphobia,   Lang::Ja) => "数字13恐怖症",
            (Self::Vestiphobia,        Lang::En) => "Vestiphobia",
            (Self::Vestiphobia,        Lang::Ja) => "衣類恐怖症",
            (Self::Wiccaphobia,        Lang::En) => "Wiccaphobia",
            (Self::Wiccaphobia,        Lang::Ja) => "魔女恐怖症",
            (Self::Xanthophobia,       Lang::En) => "Xanthophobia",
            (Self::Xanthophobia,       Lang::Ja) => "黄色恐怖症",
            (Self::Xenoglossophobia,   Lang::En) => "Xenoglossophobia",
            (Self::Xenoglossophobia,   Lang::Ja) => "外国語恐怖症",
            (Self::Xenophobia,         Lang::En) => "Xenophobia",
            (Self::Xenophobia,         Lang::Ja) => "外国人恐怖症",
            (Self::Zoophobia,          Lang::En) => "Zoophobia",
            (Self::Zoophobia,          Lang::Ja) => "動物恐怖症",
        }
    }

    pub fn all() -> &'static [Self] {
        &[
            Self::Ablutophobia,
            Self::Acrophobia,
            Self::Aerophobia,
            Self::Agoraphobia,
            Self::Alektorophobia,
            Self::Alliumphobia,
            Self::Amaxophobia,
            Self::Ancraophobia,
            Self::Androphobia,
            Self::Anglophobia,
            Self::Anthophobia,
            Self::Apotemnophobia,
            Self::Arachnophobia,
            Self::Astraphobia,
            Self::Atephobia,
            Self::Aulophobia,
            Self::Bacteriophobia,
            Self::Ballistophobia,
            Self::Basophobia,
            Self::Bibliophobia,
            Self::Botanophobia,
            Self::Caligynephobia,
            Self::Cheimaphobia,
            Self::Chronomentrophobia,
            Self::Claustrophobia,
            Self::Coulrophobia,
            Self::Cynophobia,
            Self::Demonophobia,
            Self::Demophobia,
            Self::Dentophobia,
            Self::Disposophobia,
            Self::Doraphobia,
            Self::Dromophobia,
            Self::Ecclesiophobia,
            Self::Eisoptrophobia,
            Self::Enetophobia,
            Self::Entomophobia,
            Self::Felinophobia,
            Self::Gephyrophobia,
            Self::Gerontophobia,
            Self::Gynophobia,
            Self::Haemaphobia,
            Self::Hamartophobia,
            Self::Haphophobia,
            Self::Herpetophobia,
            Self::Homichlophobia,
            Self::Hoplophobia,
            Self::Hydrophobia,
            Self::Hypnophobia,
            Self::Iatrophobia,
            Self::Ichthyophobia,
            Self::Katsaridaphobia,
            Self::Keraunophobia,
            Self::Lachanophobia,
            Self::Ligyrophobia,
            Self::Limnophobia,
            Self::Mechanophobia,
            Self::Megalophobia,
            Self::Merinthophobia,
            Self::Meteorophobia,
            Self::Monophobia,
            Self::Mysophobia,
            Self::Myxophobia,
            Self::Necrophobia,
            Self::Octophobia,
            Self::Odontophobia,
            Self::Oneirophobia,
            Self::Onomatophobia,
            Self::Ophidiophobia,
            Self::Ornithophobia,
            Self::Parasitophobia,
            Self::Pediophobia,
            Self::Phagophobia,
            Self::Pharmacophobia,
            Self::Phasmophobia,
            Self::Phenogophobia,
            Self::Pogonophobia,
            Self::Potamophobia,
            Self::Potophobia,
            Self::Pyrophobia,
            Self::Rhabdophobia,
            Self::Scotophobia,
            Self::Selenophobia,
            Self::Siderodromophobia,
            Self::Siderophobia,
            Self::Stenophobia,
            Self::Symmetrophobia,
            Self::Taphephobia,
            Self::Taurophobia,
            Self::Telephonophobia,
            Self::Teratophobia,
            Self::Thalassophobia,
            Self::Tomophobia,
            Self::Triskadekaphobia,
            Self::Vestiphobia,
            Self::Wiccaphobia,
            Self::Xanthophobia,
            Self::Xenoglossophobia,
            Self::Xenophobia,
            Self::Zoophobia,
        ]
    }
}

/// ルールブック 日本語訳版 157頁
pub enum Mania {
    Ablutomania,
    Aboulomania,
    Achluomania,
    Acromaniaheights,
    Agathomania,
    Agromania,
    Aichmomania,
    Ailuromania,
    Algomania,
    Alliomania,
    Amaxomania,
    Amenomania,
    Anthomania,
    Arithmomania,
    Asoticamania,
    Eremiomania,
    Balletmania,
    Biliokleptomania,
    Bibliomania,
    Bruxomania,
    Cacodemomania,
    Callomania,
    Cartacoethes,
    Catapedamania,
    Cheimatomania,
    Choreomania,
    Clinomania,
    Coimetormania,
    Coloromania,
    Coulromania,
    Countermania,
    Dacnomania,
    Demonomania,
    Dermatillomania,
    Dikemania,
    Dipsomania,
    Doramania,
    Doromania,
    Drapetomania,
    Ecdemiomania,
    Egomania,
    Empleomania,
    Enosimania,
    Epistemomania,
    Eremiomaniaquiet,
    Etheromania,
    Gamomania,
    Geliomania,
    Goetomania,
    Graphomania,
    Gymnomania,
    Habromania,
    Helminthomania,
    Hoplomania,
    Hydromania,
    Ichthyomania,
    Iconomania,
    Idolomania,
    Infomania,
    Klazomania,
    Kleptomania,
    Ligyromania,
    Linonomania,
    Lotterymania,
    Lypemania,
    Megalithomania,
    Melomania,
    Metromania,
    Misomania,
    Monomania,
    Mythomania,
    Nosomania,
    Notomania,
    Onomamania,
    Onomatomania,
    Onychotillomania,
    Opsomania,
    Paramania,
    Personamania,
    Phasmomania,
    Phonomania,
    Photomania,
    Antinomiamania,
    Plutomania,
    Pseudomania,
    Pyromania,
    QuestionAsking,
    Rhinotillexomania,
    Scribbleomania,
    Siderodromomania,
    Sophomania,
    Technomania,
    Thanatomania,
    Theomania,
    Titillomaniac,
    Tomomania,
    Trichotillomania,
    Typhlomania,
    Xenomania,
    Zoomania,
}

impl Mania {
    pub fn label(&self, lang: Lang) -> &'static str {
        match (self, lang) {
            (Self::Ablutomania,      Lang::En) => "Ablutomania",
            (Self::Ablutomania,      Lang::Ja) => "沐浴癖",
            (Self::Aboulomania,      Lang::En) => "Aboulomania",
            (Self::Aboulomania,      Lang::Ja) => "猶予癖",
            (Self::Achluomania,      Lang::En) => "Achluomania",
            (Self::Achluomania,      Lang::Ja) => "暗闇愛好",
            (Self::Acromaniaheights, Lang::En) => "Acromania",
            (Self::Acromaniaheights, Lang::Ja) => "高所愛好",
            (Self::Agathomania,      Lang::En) => "Agathomania",
            (Self::Agathomania,      Lang::Ja) => "親切癖",
            (Self::Agromania,        Lang::En) => "Agromania",
            (Self::Agromania,        Lang::Ja) => "広場愛好",
            (Self::Aichmomania,      Lang::En) => "Aichmomania",
            (Self::Aichmomania,      Lang::Ja) => "先鋭愛好",
            (Self::Ailuromania,      Lang::En) => "Ailuromania",
            (Self::Ailuromania,      Lang::Ja) => "猫愛好",
            (Self::Algomania,        Lang::En) => "Algomania",
            (Self::Algomania,        Lang::Ja) => "疼痛癖",
            (Self::Alliomania,       Lang::En) => "Alliomania",
            (Self::Alliomania,       Lang::Ja) => "大蒜愛好",
            (Self::Amaxomania,       Lang::En) => "Amaxomania",
            (Self::Amaxomania,       Lang::Ja) => "乗車癖",
            (Self::Amenomania,       Lang::En) => "Amenomania",
            (Self::Amenomania,       Lang::Ja) => "病的快活",
            (Self::Anthomania,       Lang::En) => "Anthomania",
            (Self::Anthomania,       Lang::Ja) => "花愛好",
            (Self::Arithmomania,     Lang::En) => "Arithmomania",
            (Self::Arithmomania,     Lang::Ja) => "計算癖",
            (Self::Asoticamania,     Lang::En) => "Asoticamania",
            (Self::Asoticamania,     Lang::Ja) => "浪費癖",
            (Self::Eremiomania,      Lang::En) => "Eremiomania",
            (Self::Eremiomania,      Lang::Ja) => "隠遁癖",
            (Self::Balletmania,      Lang::En) => "Balletmania",
            (Self::Balletmania,      Lang::Ja) => "バレエ愛好",
            (Self::Biliokleptomania, Lang::En) => "Biliokleptomania",
            (Self::Biliokleptomania, Lang::Ja) => "書籍窃盗癖",
            (Self::Bibliomania,      Lang::En) => "Bibliomania",
            (Self::Bibliomania,      Lang::Ja) => "書物愛好",
            (Self::Bruxomania,       Lang::En) => "Bruxomania",
            (Self::Bruxomania,       Lang::Ja) => "歯ぎしり癖",
            (Self::Cacodemomania,    Lang::En) => "Cacodemomania",
            (Self::Cacodemomania,    Lang::Ja) => "悪霊憑依妄想",
            (Self::Callomania,       Lang::En) => "Callomania",
            (Self::Callomania,       Lang::Ja) => "自己美愛好",
            (Self::Cartacoethes,     Lang::En) => "Cartacoethes",
            (Self::Cartacoethes,     Lang::Ja) => "地図愛好",
            (Self::Catapedamania,    Lang::En) => "Catapedamania",
            (Self::Catapedamania,    Lang::Ja) => "飛び降り愛好",
            (Self::Cheimatomania,    Lang::En) => "Cheimatomania",
            (Self::Cheimatomania,    Lang::Ja) => "寒冷愛好",
            (Self::Choreomania,      Lang::En) => "Choreomania",
            (Self::Choreomania,      Lang::Ja) => "舞踏癖",
            (Self::Clinomania,       Lang::En) => "Clinomania",
            (Self::Clinomania,       Lang::Ja) => "臥床癖",
            (Self::Coimetormania,    Lang::En) => "Coimetormania",
            (Self::Coimetormania,    Lang::Ja) => "墓地愛好",
            (Self::Coloromania,      Lang::En) => "Coloromania",
            (Self::Coloromania,      Lang::Ja) => "色彩愛好",
            (Self::Coulromania,      Lang::En) => "Coulromania",
            (Self::Coulromania,      Lang::Ja) => "道化師愛好",
            (Self::Countermania,     Lang::En) => "Countermania",
            (Self::Countermania,     Lang::Ja) => "恐怖体験追求",
            (Self::Dacnomania,       Lang::En) => "Dacnomania",
            (Self::Dacnomania,       Lang::Ja) => "殺戮癖",
            (Self::Demonomania,      Lang::En) => "Demonomania",
            (Self::Demonomania,      Lang::Ja) => "悪魔憑依妄想",
            (Self::Dermatillomania,  Lang::En) => "Dermatillomania",
            (Self::Dermatillomania,  Lang::Ja) => "皮膚むしり癖",
            (Self::Dikemania,        Lang::En) => "Dikemania",
            (Self::Dikemania,        Lang::Ja) => "正義愛好",
            (Self::Dipsomania,       Lang::En) => "Dipsomania",
            (Self::Dipsomania,       Lang::Ja) => "飲酒癖",
            (Self::Doramania,        Lang::En) => "Doramania",
            (Self::Doramania,        Lang::Ja) => "毛皮愛好",
            (Self::Doromania,        Lang::En) => "Doromania",
            (Self::Doromania,        Lang::Ja) => "贈物癖",
            (Self::Drapetomania,     Lang::En) => "Drapetomania",
            (Self::Drapetomania,     Lang::Ja) => "逃走癖",
            (Self::Ecdemiomania,     Lang::En) => "Ecdemiomania",
            (Self::Ecdemiomania,     Lang::Ja) => "放浪癖",
            (Self::Egomania,         Lang::En) => "Egomania",
            (Self::Egomania,         Lang::Ja) => "自己中心癖",
            (Self::Empleomania,      Lang::En) => "Empleomania",
            (Self::Empleomania,      Lang::Ja) => "労働癖",
            (Self::Enosimania,       Lang::En) => "Enosimania",
            (Self::Enosimania,       Lang::Ja) => "罪悪妄想",
            (Self::Epistemomania,    Lang::En) => "Epistemomania",
            (Self::Epistemomania,    Lang::Ja) => "知識愛好",
            (Self::Eremiomaniaquiet, Lang::En) => "Eremiomania (quiet)",
            (Self::Eremiomaniaquiet, Lang::Ja) => "静寂癖",
            (Self::Etheromania,      Lang::En) => "Etheromania",
            (Self::Etheromania,      Lang::Ja) => "エーテル依存",
            (Self::Gamomania,        Lang::En) => "Gamomania",
            (Self::Gamomania,        Lang::Ja) => "求婚癖",
            (Self::Geliomania,       Lang::En) => "Geliomania",
            (Self::Geliomania,       Lang::Ja) => "強迫的笑い",
            (Self::Goetomania,       Lang::En) => "Goetomania",
            (Self::Goetomania,       Lang::Ja) => "魔術愛好",
            (Self::Graphomania,      Lang::En) => "Graphomania",
            (Self::Graphomania,      Lang::Ja) => "筆記癖",
            (Self::Gymnomania,       Lang::En) => "Gymnomania",
            (Self::Gymnomania,       Lang::Ja) => "裸体愛好",
            (Self::Habromania,       Lang::En) => "Habromania",
            (Self::Habromania,       Lang::Ja) => "愉快妄想",
            (Self::Helminthomania,   Lang::En) => "Helminthomania",
            (Self::Helminthomania,   Lang::Ja) => "蠕虫愛好",
            (Self::Hoplomania,       Lang::En) => "Hoplomania",
            (Self::Hoplomania,       Lang::Ja) => "火器愛好",
            (Self::Hydromania,       Lang::En) => "Hydromania",
            (Self::Hydromania,       Lang::Ja) => "飲水癖",
            (Self::Ichthyomania,     Lang::En) => "Ichthyomania",
            (Self::Ichthyomania,     Lang::Ja) => "魚類愛好",
            (Self::Iconomania,       Lang::En) => "Iconomania",
            (Self::Iconomania,       Lang::Ja) => "図像愛好",
            (Self::Idolomania,       Lang::En) => "Idolomania",
            (Self::Idolomania,       Lang::Ja) => "偶像愛好",
            (Self::Infomania,        Lang::En) => "Infomania",
            (Self::Infomania,        Lang::Ja) => "情報収集癖",
            (Self::Klazomania,       Lang::En) => "Klazomania",
            (Self::Klazomania,       Lang::Ja) => "叫び癖",
            (Self::Kleptomania,      Lang::En) => "Kleptomania",
            (Self::Kleptomania,      Lang::Ja) => "窃盗癖",
            (Self::Ligyromania,      Lang::En) => "Ligyromania",
            (Self::Ligyromania,      Lang::Ja) => "騒音癖",
            (Self::Linonomania,      Lang::En) => "Linonomania",
            (Self::Linonomania,      Lang::Ja) => "紐愛好",
            (Self::Lotterymania,     Lang::En) => "Lotterymania",
            (Self::Lotterymania,     Lang::Ja) => "宝くじ愛好",
            (Self::Lypemania,        Lang::En) => "Lypemania",
            (Self::Lypemania,        Lang::Ja) => "重度抑鬱",
            (Self::Megalithomania,   Lang::En) => "Megalithomania",
            (Self::Megalithomania,   Lang::Ja) => "巨石愛好",
            (Self::Melomania,        Lang::En) => "Melomania",
            (Self::Melomania,        Lang::Ja) => "音楽愛好",
            (Self::Metromania,       Lang::En) => "Metromania",
            (Self::Metromania,       Lang::Ja) => "作詩癖",
            (Self::Misomania,        Lang::En) => "Misomania",
            (Self::Misomania,        Lang::Ja) => "憎悪癖",
            (Self::Monomania,        Lang::En) => "Monomania",
            (Self::Monomania,        Lang::Ja) => "偏執愛好",
            (Self::Mythomania,       Lang::En) => "Mythomania",
            (Self::Mythomania,       Lang::Ja) => "虚言癖",
            (Self::Nosomania,        Lang::En) => "Nosomania",
            (Self::Nosomania,        Lang::Ja) => "疾病妄想",
            (Self::Notomania,        Lang::En) => "Notomania",
            (Self::Notomania,        Lang::Ja) => "記録癖",
            (Self::Onomamania,       Lang::En) => "Onomamania",
            (Self::Onomamania,       Lang::Ja) => "名前愛好",
            (Self::Onomatomania,     Lang::En) => "Onomatomania",
            (Self::Onomatomania,     Lang::Ja) => "単語反復癖",
            (Self::Onychotillomania, Lang::En) => "Onychotillomania",
            (Self::Onychotillomania, Lang::Ja) => "爪むしり癖",
            (Self::Opsomania,        Lang::En) => "Opsomania",
            (Self::Opsomania,        Lang::Ja) => "美食愛好",
            (Self::Paramania,        Lang::En) => "Paramania",
            (Self::Paramania,        Lang::Ja) => "不満癖",
            (Self::Personamania,     Lang::En) => "Personamania",
            (Self::Personamania,     Lang::Ja) => "仮面愛好",
            (Self::Phasmomania,      Lang::En) => "Phasmomania",
            (Self::Phasmomania,      Lang::Ja) => "幽霊愛好",
            (Self::Phonomania,       Lang::En) => "Phonomania",
            (Self::Phonomania,       Lang::Ja) => "殺人癖",
            (Self::Photomania,       Lang::En) => "Photomania",
            (Self::Photomania,       Lang::Ja) => "光線愛好",
            (Self::Antinomiamania,   Lang::En) => "Antinomiamania",
            (Self::Antinomiamania,   Lang::Ja) => "反社会的行動癖",
            (Self::Plutomania,       Lang::En) => "Plutomania",
            (Self::Plutomania,       Lang::Ja) => "富愛好",
            (Self::Pseudomania,      Lang::En) => "Pseudomania",
            (Self::Pseudomania,      Lang::Ja) => "虚偽癖",
            (Self::Pyromania,        Lang::En) => "Pyromania",
            (Self::Pyromania,        Lang::Ja) => "放火癖",
            (Self::QuestionAsking,   Lang::En) => "Question-Asking Mania",
            (Self::QuestionAsking,   Lang::Ja) => "質問癖",
            (Self::Rhinotillexomania,Lang::En) => "Rhinotillexomania",
            (Self::Rhinotillexomania,Lang::Ja) => "鼻ほじり癖",
            (Self::Scribbleomania,   Lang::En) => "Scribbleomania",
            (Self::Scribbleomania,   Lang::Ja) => "落書き癖",
            (Self::Siderodromomania, Lang::En) => "Siderodromomania",
            (Self::Siderodromomania, Lang::Ja) => "鉄道愛好",
            (Self::Sophomania,       Lang::En) => "Sophomania",
            (Self::Sophomania,       Lang::Ja) => "知性誇大妄想",
            (Self::Technomania,      Lang::En) => "Technomania",
            (Self::Technomania,      Lang::Ja) => "技術愛好",
            (Self::Thanatomania,     Lang::En) => "Thanatomania",
            (Self::Thanatomania,     Lang::Ja) => "死の呪い妄想",
            (Self::Theomania,        Lang::En) => "Theomania",
            (Self::Theomania,        Lang::Ja) => "神格妄想",
            (Self::Titillomaniac,    Lang::En) => "Titillomaniac",
            (Self::Titillomaniac,    Lang::Ja) => "掻き傷癖",
            (Self::Tomomania,        Lang::En) => "Tomomania",
            (Self::Tomomania,        Lang::Ja) => "手術愛好",
            (Self::Trichotillomania, Lang::En) => "Trichotillomania",
            (Self::Trichotillomania, Lang::Ja) => "抜毛癖",
            (Self::Typhlomania,      Lang::En) => "Typhlomania",
            (Self::Typhlomania,      Lang::Ja) => "失明妄想",
            (Self::Xenomania,        Lang::En) => "Xenomania",
            (Self::Xenomania,        Lang::Ja) => "異国愛好",
            (Self::Zoomania,         Lang::En) => "Zoomania",
            (Self::Zoomania,         Lang::Ja) => "動物愛好",
        }
    }

    pub fn all() -> &'static [Self] {
        &[
            Self::Ablutomania,
            Self::Aboulomania,
            Self::Achluomania,
            Self::Acromaniaheights,
            Self::Agathomania,
            Self::Agromania,
            Self::Aichmomania,
            Self::Ailuromania,
            Self::Algomania,
            Self::Alliomania,
            Self::Amaxomania,
            Self::Amenomania,
            Self::Anthomania,
            Self::Arithmomania,
            Self::Asoticamania,
            Self::Eremiomania,
            Self::Balletmania,
            Self::Biliokleptomania,
            Self::Bibliomania,
            Self::Bruxomania,
            Self::Cacodemomania,
            Self::Callomania,
            Self::Cartacoethes,
            Self::Catapedamania,
            Self::Cheimatomania,
            Self::Choreomania,
            Self::Clinomania,
            Self::Coimetormania,
            Self::Coloromania,
            Self::Coulromania,
            Self::Countermania,
            Self::Dacnomania,
            Self::Demonomania,
            Self::Dermatillomania,
            Self::Dikemania,
            Self::Dipsomania,
            Self::Doramania,
            Self::Doromania,
            Self::Drapetomania,
            Self::Ecdemiomania,
            Self::Egomania,
            Self::Empleomania,
            Self::Enosimania,
            Self::Epistemomania,
            Self::Eremiomaniaquiet,
            Self::Etheromania,
            Self::Gamomania,
            Self::Geliomania,
            Self::Goetomania,
            Self::Graphomania,
            Self::Gymnomania,
            Self::Habromania,
            Self::Helminthomania,
            Self::Hoplomania,
            Self::Hydromania,
            Self::Ichthyomania,
            Self::Iconomania,
            Self::Idolomania,
            Self::Infomania,
            Self::Klazomania,
            Self::Kleptomania,
            Self::Ligyromania,
            Self::Linonomania,
            Self::Lotterymania,
            Self::Lypemania,
            Self::Megalithomania,
            Self::Melomania,
            Self::Metromania,
            Self::Misomania,
            Self::Monomania,
            Self::Mythomania,
            Self::Nosomania,
            Self::Notomania,
            Self::Onomamania,
            Self::Onomatomania,
            Self::Onychotillomania,
            Self::Opsomania,
            Self::Paramania,
            Self::Personamania,
            Self::Phasmomania,
            Self::Phonomania,
            Self::Photomania,
            Self::Antinomiamania,
            Self::Plutomania,
            Self::Pseudomania,
            Self::Pyromania,
            Self::QuestionAsking,
            Self::Rhinotillexomania,
            Self::Scribbleomania,
            Self::Siderodromomania,
            Self::Sophomania,
            Self::Technomania,
            Self::Thanatomania,
            Self::Theomania,
            Self::Titillomaniac,
            Self::Tomomania,
            Self::Trichotillomania,
            Self::Typhlomania,
            Self::Xenomania,
            Self::Zoomania,
        ]
    }
}